language: python
python:
  - 3.3
  - 3.4
  - 3.5
  - 3.6
install:
  - pip install pycodestyle
  - pip install codecov
script:
  - pycodestyle .
  - coverage run --source=douban_rating setup.py test
after_success:
  - codecov
